name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
         fetch-tags: true
      - uses: actions/setup-python@v5
        with:
         python-version: '3.11'
         cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install sphinx sphinx_autodoc_typehints sphinx_rtd_theme myst_parser sphinx-multiversion
          pip install ../MatDBForge
          echo "## Done"
      - name: Apidoc
        run: |
          sphinx-apidoc -o ./docs/source ./src/MatDBForge/ "*benchmarks*" "*display_db*" --remove-old  -f
      - name: Sphinx build
        run: |
          sphinx-multiversion docs _build
      - name: Create index.html pointing to master
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Redirecting to master branch</title>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=./master/index.html">
            <link rel="canonical" href="https://pol-sb.github.io/MatDBForge/master/index.html">
          </head>
          </html>' > _build/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
