name: Build and Deploy Documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install sphinx sphinx_autodoc_typehints sphinx_rtd_theme myst_parser sphinx-multiversion
          pip install .

      - name: Cache the Sphinx build environment
        uses: actions/cache@v4
        with:
          path: docs/.doctrees
          key: ${{ runner.os }}-sphinx-doctrees-${{ hashFiles('docs/**/*', 'src/**/*') }}
          restore-keys: |
            ${{ runner.os }}-sphinx-doctrees-

      - name: Generate API documentation
        run: sphinx-apidoc -o ./docs/source ./src/MatDBForge/ "*benchmarks*" "*display_db*" --remove-old -f

      - name: Build all documentation versions
        run: sphinx-multiversion docs _build/html

      - name: Create index.html redirect
        run: |
          echo '<!DOCTYPE html><html><head><title>Redirecting...</title><meta http-equiv="refresh" content="0; url=./master/index.html"></head></html>' > _build/html/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
          force_orphan: true # Recommended by sphinx-multiversion for a clean deployment
